# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rest-app'
    scrape_interval: 10s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: [ 'rest:8080' ]
  - job_name: 'proxy'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'proxy:8082' ]
  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgresql-exporter:9187' ]

